'use strict';

/**
 * Step: Git PR / Commit Creation
 *
 * Create git commit and optionally PR if not in dry-run mode.
 *
 * Priority: 70
 * After: changelog
 */

const { TeardownStep } = require('../teardown-step');
const { HOOK_EVENTS } = require('../constants');

class GitPrStep extends TeardownStep {
  constructor() {
    super({
      name: 'git-pr',
      description: 'Create git commit and optionally PR',
      priority: 70,
      after: ['changelog'],
    });
  }

  async execute(ctx) {
    const { orch } = ctx;

    try {
      // Skip if no changes or dry-run
      if (orch.dryRun || !orch._gitHelper) return;

      const goal = (orch._currentGoal || ctx.extra.goal || '').slice(0, 60);
      const commitResult = orch._gitHelper.autoCommit(
        `workflow: ${goal || 'teardown'}`
      );

      if (commitResult?.committed) {
        console.log(`[Orchestrator] 🔀 Git: committed ${commitResult.filesChanged} file(s)`);

        // Auto PR if configured
        if (orch._config?.git?.autoPR && orch._gitHelper.createPR) {
          const prResult = await orch._gitHelper.createPR({
            title: `workflow: ${goal || 'Automated workflow changes'}`,
            body: `Auto-generated by WorkFlowAgent.\n\nGoal: ${goal || 'N/A'}`,
          });
          if (prResult?.url) {
            console.log(`[Orchestrator] 🔀 PR created: ${prResult.url}`);
            await orch.hooks.emit(HOOK_EVENTS.PR_CREATED, {
              url: prResult.url,
              number: prResult.number,
            });
          }
        }
      }
    } catch (gitErr) {
      console.warn(`[Orchestrator] ⚠️  Git commit/PR failed (non-fatal): ${gitErr.message}`);
    }
  }
}

module.exports = { GitPrStep };
