/**
 * workflow.config.js – Project Workflow Configuration
 *
 * Auto-generated by: node workflow/init-project.js
 * Detected tech stack: JavaScript / Node.js
 * Generated at: 2026-04-01T04:10:52.651Z
 *
 * You can customise this file at any time.
 * Re-run: node workflow/init-project.js  to apply changes.
 *
 * NOTE: projectName, techStack, sourceExtensions, and ignoreDirs are
 * intentionally omitted. They are auto-detected at runtime by detectTechStack()
 * and do not need to be configured manually. If you want to override them,
 * uncomment and edit the overrides section below.
 */

'use strict';

module.exports = {
  // ─── Runtime-Detected (uncomment to override) ─────────────────────────────
  // These are auto-detected at init time. Only set them if the detection is wrong.
  // projectName: 'WorkFlowAgent',
  // techStack: 'JavaScript + Node.js',
  // sourceExtensions: ['.js', '.mjs'],
  // ignoreDirs: ['node_modules', '.git', 'dist', 'build', 'output'],

  // ─── Code Graph ──────────────────────────────────────────────────────────────
  // CodeGraph auto-scans ALL supported languages (.js, .ts, .cs, .lua, .go, .py, .dart).
  // No extensions config needed. Use scopeDirs for large monorepos only.
  codeGraph: {
    scopeDirs: [],             // Large monorepo only: ['packages/core', 'lua']. Empty = full scan
  },

  // ─── Remote Workflow Reference ──────────────────────────────────────────────
  // Point to an external WorkFlowAgent installation instead of copying workflow/
  // into this project. All IDE Agent Bridge commands will use this path.
  // Leave as null to use the local workflow/ directory inside this project.
  workflowSource: null,

  // ─── Automated Verification Loop ─────────────────────────────────────────
  testCommand: 'npm test',
  testProfile: 'fast', // P0: fast=smoke+unit, full=smoke+unit+integration

  autoFixLoop: {
    enabled: true,
    maxFixRounds: 2,
    failOnUnfixed: false,
  },

  // ─── Project Architecture Profile ─────────────────────────────────────────
  // Auto-populated by ProjectProfiler during init. Contains deep analysis of
  // frameworks, architecture patterns, data layer, communication, testing, etc.
  // Consumed by Architect/Developer agents for context-aware decisions.
  projectProfile: {
      "root": "C:\\workspace\\WorkFlowAgent",
      "primaryLanguage": "javascript",
      "frameworks": [],
      "architecture": {
          "pattern": "Unknown",
          "layers": [
              "core"
          ],
          "confidence": 0
      },
      "dataLayer": {
          "orm": [],
          "configFiles": [],
          "databases": []
      },
      "testing": {
          "frameworks": [
              "unittest",
              "XCTest"
          ]
      },
      "communication": [],
      "infrastructure": {},
      "monorepo": {
          "isMonorepo": false,
          "tool": null,
          "packages": []
      },
      "apis": [],
      "entryPoints": [],
      "analyzedAt": "2026-04-01T04:10:52.661Z",
      "analysisMs": 6
  },  // Will be populated by init-project.js → ProjectProfiler

  // ─── Built-in Skills ─────────────────────────────────────────────────────
  builtinSkills: [
    {
        name: "workflow-orchestration",
        description: "Multi-agent workflow orchestration SOP",
        domains: [
            "workflow",
            "orchestration"
        ]
    },
    {
        name: "code-review",
        description: "Code review checklist and best practices",
        domains: [
            "quality",
            "review"
        ]
    },
    {
        name: "javascript-dev",
        description: "JavaScript development patterns",
        domains: [
            "frontend",
            "backend",
            "javascript"
        ]
    }
],

  // ─── Default Skills ───────────────────────────────────────────────────────
  defaultSkills: {
    ".js": "javascript-dev"
},

  // ─── Classification Rules ─────────────────────────────────────────────────
  classificationRules: [],

  // ─── IDE Configuration (ADR-37) ────────────────────────────────────────────
  // IDE-First strategy: prefer IDE-native tools over self-built ones
  // When running inside an IDE (Cursor, VS Code:, Claude Code:, Windsurf),
  // the system will automatically detect and use IDE capabilities.
  // Self-built modules (CodeGraph, LSPAdapter) serve as fallback only.
  ide: {
    // Force IDE detection (optional)
    // forceIDE: 'vscode',        // Force specific IDE: 'vscode', 'cursor', 'claude', 'windsurf'
    // forceStandalone: false,    // Force standalone mode (no IDE) - default: false

    // Enable IDE-first routing (default: true)
    // When true, prefers IDE tools: codebase_search, grep_search, view_code_item
    // When false, uses self-built modules as primary
    ideFirstRouting: true,

    // IDE capabilities configuration (auto-detected if null)
    // Manually specify which IDE capabilities to use
    capabilities: null,
    // Example:
    // capabilities: {
    //   codebaseSearch: true,
    //   grepSearch: true,
    //   viewCodeItem: true,
    //   builtinLSP: true,
    // }
  },

  // ─── Scheduler (Session-Start Overdue Detection) ────────────────────────────
  // Replaces background scheduler with "check on session start" pattern.
  // Run `scheduler-check` at each session start to detect overdue tasks.
  scheduler: {
    enabled: true,
    tasks: [
      { command: 'experience-evolve', cron: 'weekly', args: [] },
      { command: 'skill-refine-check', cron: 'weekly', args: [] },
      { command: 'deep-audit', cron: 'weekly', args: ['--incremental'] },
      { command: 'regression-check', cron: 'monthly', args: [] },
      { command: 'experience-health', cron: 'daily', args: [] },
    ],
  },

  // ─── Health Monitoring (B + D) ─────────────────────────────────────────────
  // B: Rolling-window trend alerts
  // D: Externalized unified scoring parameters
  healthMonitoring: {
    scoring: {
      model: 'unified-v1',
      weights: {
        completeness: 0.35,
        process: 0.20,
        delivery: 0.30,
        detection: 0.15,
      },
      penalties: {
        missingStage: 20,
        socraticMax: 20,
        metricsGatePerFailedStage: 5,
        metricsGateMax: 25,
      },
      gradeThresholds: {
        A: 90,
        B: 80,
        C: 70,
        D: 60,
      },
    },
    trend: {
      enabled: true,
      windowSize: 5,
      minSessions: 3,
      degradationThreshold: 8,
      lowScoreThreshold: 75,
      maxHistoryEntries: 200,
    },
  },

  // ─── Module-Level Logging (ARCHITECTURE.md D-1) ────────────────────────────
  // Controls module-level monitoring logs written to workflow-progress.log
  // Enables fine-grained visibility into Experience, CodeGraph, Skill, Evolution modules
  moduleLog: {
    enabled: true,               // Master switch for module-level logging
    defaultLevel: 'INFO',        // Default log level: 'INFO' | 'WARN' | 'ERROR' | 'DETAIL'
    moduleOverrides: {},         // Per-module level overrides (e.g., { Experience: 'WARN' })
    maxEntriesPerSession: 200,   // Safety limit to prevent log explosion
  },
};
