/*
 * CodeGraph layered index tests.
 * Verifies output/code-graph-index.json + output/code-graph-shards/*.json are
 * generated by default, while legacy output/code-graph.json requires an explicit flag.
 */

'use strict';

const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { CodeGraph } = require('./code-graph');

let passed = 0;
let failed = 0;

function test(name, fn) {
  try {
    Promise.resolve(fn()).then(() => {
      passed++;
      console.log(`✅ ${name}`);
    }).catch(err => {
      failed++;
      console.error(`❌ ${name}`);
      console.error(`   ${err.message}`);
    });
  } catch (err) {
    failed++;
    console.error(`❌ ${name}`);
    console.error(`   ${err.message}`);
  }
}

function tmpDir() {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'code-graph-layered-'));
}

function addSymbol(graph, file, name, kind = 'function', line = 1) {
  const id = `${file}::${name}`;
  graph._symbols.set(id, { id, file, name, kind, line, signature: `${name}()`, summary: '' });
  return id;
}

async function run() {
  console.log('\n=== CodeGraph Layered Index Tests ===\n');

  await new Promise(resolve => {
    test('writes index + per-module shards without legacy graph by default', async () => {
      const out = tmpDir();
      try {
        const graph = new CodeGraph({ projectRoot: out, outputDir: out });
        graph._ideSearchAvailable = false;
        graph._lazyLoaded = true;

        const a = addSymbol(graph, 'src/core/a.js', 'CoreService', 'class', 1);
        const b = addSymbol(graph, 'src/core/b.js', 'helper', 'function', 2);
        const c = addSymbol(graph, 'src/ui/view.js', 'ViewController', 'class', 3);
        graph._callEdges.set(c, [a, b]);
        graph._callEdges.set(a, [b]);
        graph._importEdges.set('src/ui/view.js', ['src/core/a.js']);

        await graph._writeOutput();
        assert(!fs.existsSync(path.join(out, 'code-graph.json')), 'legacy code-graph.json should be disabled by default');

        const indexPath = path.join(out, 'code-graph-index.json');
        assert(fs.existsSync(indexPath), 'code-graph-index.json should exist');
        const index = JSON.parse(fs.readFileSync(indexPath, 'utf8'));
        assert.strictEqual(index.version, 1);
        assert(index.modules.length >= 2, 'should have at least two modules');
        assert(index.symbolLookupTable.CoreService, 'symbolLookupTable should map CoreService');
        assert(index.topCrossModuleEdges.length >= 1, 'should include cross-module edges');

        const shardDir = path.join(out, 'code-graph-shards');
        assert(fs.existsSync(shardDir), 'shard dir should exist');
        const shardFiles = fs.readdirSync(shardDir).filter(f => f.endsWith('.json'));
        assert(shardFiles.length >= 2, 'should write per-module shards');
        const shard = JSON.parse(fs.readFileSync(path.join(shardDir, shardFiles[0]), 'utf8'));
        assert(Array.isArray(shard.symbols), 'shard should contain symbols');
        assert(shard.callEdges && typeof shard.callEdges === 'object', 'shard should contain callEdges');
        assert(Array.isArray(shard.inboundEdges), 'shard should contain inboundEdges');
        assert(Array.isArray(shard.outboundEdges), 'shard should contain outboundEdges');
      } finally {
        fs.rmSync(out, { recursive: true, force: true });
      }
    });
    test('writes legacy graph only when explicitly enabled', async () => {
      const out = tmpDir();
      try {
        const graph = new CodeGraph({ projectRoot: out, outputDir: out, writeLegacyGraph: true });
        graph._ideSearchAvailable = false;
        graph._lazyLoaded = true;
        addSymbol(graph, 'src/core/a.js', 'CoreService', 'class', 1);
        await graph._writeOutput();
        assert(fs.existsSync(path.join(out, 'code-graph.json')), 'legacy code-graph.json should exist when enabled');
      } finally {
        fs.rmSync(out, { recursive: true, force: true });
      }
    });

    // ── Pass-2: auto-drill-down split ─────────────────────────────────────

    test('Pass-2: oversized module auto-splits along depth-2 boundaries', async () => {
      const prevEnv = process.env.WF_CODE_GRAPH_MAX_SYMBOLS_PER_SHARD;
      process.env.WF_CODE_GRAPH_MAX_SYMBOLS_PER_SHARD = '100';  // force split
      const out = tmpDir();
      try {
        const graph = new CodeGraph({ projectRoot: out, outputDir: out });
        graph._ideSearchAvailable = false;
        graph._lazyLoaded = true;
        // 'Assets' is a FRAMEWORK_ROOT, so depth-1 name is 'Scripts'.
        // Place files under TWO different sub-dirs (UICtrl + Systems) so Pass-2
        // can split 'Scripts' by depth-2 into 'Scripts/UICtrl' + 'Scripts/Systems'.
        for (let i = 0; i < 70; i++) {
          addSymbol(graph, `Assets/Scripts/UICtrl/F${i}.cs`, `U${i}`, 'class', i + 1);
        }
        for (let i = 0; i < 70; i++) {
          addSymbol(graph, `Assets/Scripts/Systems/F${i}.cs`, `Y${i}`, 'class', i + 1);
        }
        // A smaller depth-1 module that should NOT split (under threshold)
        for (let i = 0; i < 40; i++) {
          addSymbol(graph, `Assets/Extensions/PSD2UI/F${i}.cs`, `E${i}`, 'class', i + 1);
        }
        await graph._writeOutput();
        const indexPath = path.join(out, 'code-graph-index.json');
        const index = JSON.parse(fs.readFileSync(indexPath, 'utf8'));
        const moduleNames = index.modules.map(m => m.name);
        // 'Scripts' (140 symbols) must be split; 'Extensions' (40) stays single.
        assert(!moduleNames.includes('Scripts'),
          `expected Scripts to be split; got modules=${moduleNames.join(',')}`);
        assert(moduleNames.includes('Scripts/UICtrl'),
          `expected Scripts/UICtrl sub-module, got ${moduleNames.join(',')}`);
        assert(moduleNames.includes('Scripts/Systems'),
          `expected Scripts/Systems sub-module, got ${moduleNames.join(',')}`);
        assert(moduleNames.includes('Extensions'),
          `Extensions (40 syms < 100) should NOT split; got ${moduleNames.join(',')}`);
        // Every module should be within the threshold (or hit the depth cap)
        for (const m of index.modules) {
          assert(m.symbolCount <= 100 || m.name.split('/').length >= 3,
            `module ${m.name} exceeds cap at depth<3 (symbols=${m.symbolCount})`);
        }
      } finally {
        fs.rmSync(out, { recursive: true, force: true });
        if (prevEnv === undefined) delete process.env.WF_CODE_GRAPH_MAX_SYMBOLS_PER_SHARD;
        else process.env.WF_CODE_GRAPH_MAX_SYMBOLS_PER_SHARD = prevEnv;
      }
    });

    test('Pass-2: small project does NOT trigger split', async () => {
      // Use default threshold (15000); 3 symbols won't trigger.
      const out = tmpDir();
      try {
        const graph = new CodeGraph({ projectRoot: out, outputDir: out });
        graph._ideSearchAvailable = false;
        graph._lazyLoaded = true;
        addSymbol(graph, 'src/core/a.js', 'A', 'class', 1);
        addSymbol(graph, 'src/core/b.js', 'B', 'function', 2);
        addSymbol(graph, 'src/ui/v.js', 'V', 'class', 3);
        await graph._writeOutput();
        const index = JSON.parse(fs.readFileSync(path.join(out, 'code-graph-index.json'), 'utf8'));
        // `core` and `ui` both at depth-1 (src skipped, FRAMEWORK_ROOTS)
        const names = index.modules.map(m => m.name);
        assert(names.includes('core'), `expected 'core' at depth-1, got ${names.join(',')}`);
        assert(names.includes('ui'), `expected 'ui' at depth-1, got ${names.join(',')}`);
        assert(!names.some(n => n.includes('/')),
          `no compound names expected in small project, got ${names.join(',')}`);
      } finally {
        fs.rmSync(out, { recursive: true, force: true });
      }
    });

    test('Pass-2: env WF_CODE_GRAPH_MAX_SYMBOLS_PER_SHARD=999999 disables split', async () => {
      const prevEnv = process.env.WF_CODE_GRAPH_MAX_SYMBOLS_PER_SHARD;
      process.env.WF_CODE_GRAPH_MAX_SYMBOLS_PER_SHARD = '999999';
      const out = tmpDir();
      try {
        const graph = new CodeGraph({ projectRoot: out, outputDir: out });
        graph._ideSearchAvailable = false;
        graph._lazyLoaded = true;
        for (let i = 0; i < 100; i++) {
          addSymbol(graph, `Assets/Scripts/F${i}.cs`, `S${i}`, 'class', i + 1);
        }
        await graph._writeOutput();
        const index = JSON.parse(fs.readFileSync(path.join(out, 'code-graph-index.json'), 'utf8'));
        const names = index.modules.map(m => m.name);
        // With split disabled, the depth-1 module name should remain
        assert(names.includes('Scripts') || names.includes('Assets/Scripts') === false,
          `with split disabled expected single depth-1 module; got ${names.join(',')}`);
        assert.strictEqual(index.modules.length, 1,
          `with split disabled expected 1 module, got ${index.modules.length}`);
      } finally {
        fs.rmSync(out, { recursive: true, force: true });
        if (prevEnv === undefined) delete process.env.WF_CODE_GRAPH_MAX_SYMBOLS_PER_SHARD;
        else process.env.WF_CODE_GRAPH_MAX_SYMBOLS_PER_SHARD = prevEnv;
      }
    });

    test('Pass-2: edges preserved after split (no symbol/edge loss)', async () => {
      const prevEnv = process.env.WF_CODE_GRAPH_MAX_SYMBOLS_PER_SHARD;
      process.env.WF_CODE_GRAPH_MAX_SYMBOLS_PER_SHARD = '50';
      const out = tmpDir();
      try {
        const graph = new CodeGraph({ projectRoot: out, outputDir: out });
        graph._ideSearchAvailable = false;
        graph._lazyLoaded = true;
        // 60 symbols in Assets/Scripts/A and 60 in Assets/Scripts/B; add some edges
        const ids = [];
        for (let i = 0; i < 60; i++) {
          ids.push(addSymbol(graph, `Assets/Scripts/A/F${i}.cs`, `A${i}`, 'class', i + 1));
        }
        for (let i = 0; i < 60; i++) {
          ids.push(addSymbol(graph, `Assets/Scripts/B/F${i}.cs`, `B${i}`, 'class', i + 1));
        }
        // Cross-subdir edge: A0 → B0
        graph._callEdges.set(ids[0], [ids[60]]);
        await graph._writeOutput();
        const index = JSON.parse(fs.readFileSync(path.join(out, 'code-graph-index.json'), 'utf8'));
        const totalSymbols = index.modules.reduce((s, m) => s + m.symbolCount, 0);
        assert.strictEqual(totalSymbols, 120,
          `symbols should be preserved after split; got total=${totalSymbols}`);
        // Should have a cross-module edge between sub-modules
        const hasCross = index.topCrossModuleEdges.some(e =>
          e.fromModule !== e.toModule && e.count > 0
        );
        assert(hasCross, 'cross-module edge between sub-modules should be tracked');
      } finally {
        fs.rmSync(out, { recursive: true, force: true });
        if (prevEnv === undefined) delete process.env.WF_CODE_GRAPH_MAX_SYMBOLS_PER_SHARD;
        else process.env.WF_CODE_GRAPH_MAX_SYMBOLS_PER_SHARD = prevEnv;
      }
    });
    setTimeout(resolve, 500);
  });

  console.log('\n==================================================');
  console.log(`Results: ${passed}/${passed + failed} passed`);
  console.log('==================================================\n');
  if (failed > 0) process.exit(1);
}

run();
